language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: meme-generator-capstone
  api_key:
    secure: fxsaXNq2wfYL96qjEZnans7t1M3wFDFYqtJ7lWFKgPewaOPQSZXkET3uSO/cYOHrZjumRY8k/Id8nUY+OMcpN0L87gmPqZIgzuBxKYF/PPSVJqbfwoHkwF1qMgZn4s/JeoJf9HXm0yXc9liN6Ml+kgJ2AOtVdZvQ5ss1AVWEFtIQkBGSgd4nbbIPBFeI5S092SDjvdohfpX4NF0fsCiwG6uYPvrasKhbB3xgWc4s5DoJmRzjb4xD8j8TGRC++BvHNLWzEIEz7A33Ln3SSoNEEPZLgCDxN1pOwpZ9WdfiVUQIyf9SBJaVDQffWXOX/1Usg9tM7xI8RNPgJK1lhheQfzLallYnmGvtQLXbcPLoNu/L+M0FPxP80CX2TCminWU1HP1RjuR5WebBXYMswiSZcUn9uS3t5K6EnA7NtOw7KOT7YltMim3Cp6ltsZvJ7ZIHCn9/hEaf6lJ0qKG2hxbmnvHAMhAbIC8GwFthPvQE/t962RoxOLVU3YgoPkE+G/goyu0zcIa4T/4Js6T3Emrc9kIl1tRv5OxrUies/C5/aPWOK1NMRZT7q8iHzOp8WJ1lpvpQhVQS20dpDQeamJsp4SMkjH5iMAnE/EBkBhgb+VVWLCbHRwAastsHbTfAsto6muo3oeRlDTIQPoeeNNrAi0Z7gwxgBNcHlKSeBn3CqMc=
